// Reconciliation/Reconciliation.Vue/src/components/Home.vue
<template>
  <div class="container">
    <h4 class="text-center mt-5">We are in vue app</h4>
    <h1 class="text-center mt-5" v-if="!grid">Loading...</h1>

    <div class="row">
      <div class="col-12" v-if="grid">
        <table class="table table-striped table-bordered">
          <thead>
            <tr class="text-center">
              <th colspan="14">Year {{grid.year}}</th>
            </tr>
            <tr class="text-center">
              <th></th>
              <th v-for="title in grid.titles" :key="title.month">{{title.monthDisplayName}}</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in grid.statements" :key="row.month" class="table-secondary">
              <td>{{row.title}}</td>
              <td v-for="col in row.values" :key="col.month">{{col.amount}}</td>
            </tr>

            <tr
              v-for="row in grid.rows"
              :key="row.month"
              v-bind:class="{ 'table-success': row.flag==1, 'table-danger': row.flag==2, }"
            >
              <td>{{row.incomeOrExpenseTypeName}}</td>

              <td v-for="col in row.columns" :key="col.month" @click>{{col.amount}}</td>
            </tr>

            <tr v-for="row in grid.results" :key="row.month" class="table-secondary">
              <td>{{row.title}}</td>
              <td v-for="col in row.values" :key="col.month">{{col.amount}}</td>
            </tr>
          </tbody>
        </table>

        <div class="row mb-5">
          <div class="col-12 text-center">
            <span class="badge badge-secondary">Readonly</span>
            &nbsp;&nbsp;
            <span class="badge badge-success">Income</span>
            &nbsp;&nbsp;
            <span class="badge badge-danger">Expense</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { YearlyReconciliationGridDto } from "../models/dtos/yearly-reconsiliation-grid-dto.model";
import { AxiosResponse } from "axios";

@Component
export default class Home extends Vue {
  @Prop() private grid: YearlyReconciliationGridDto | undefined;
  @Prop() private inEditing: boolean | undefined;
  @Prop() private editingRowIndex: number | undefined;
  @Prop() private editingColIndex: number | undefined;

  constructor() {
    super();

    this.getAll();
  }

  getAll() {
    Vue.axios
      .get<YearlyReconciliationGridDto>(
        "http://localhost:49660/reconciliation/yearly-table"
      )
      .then(response => {
        this.grid = response.data;
      });
  }

  editCell(rowIndex: number, colIndex: number) {
    this.inEditing = true;
    this.editingRowIndex = rowIndex;
    this.editingColIndex = colIndex;
  }
}
</script>

<style scoped>
</style>

// Reconciliation/Reconciliation.React/ClientApp/src/components/Home.js
import React, { Component } from 'react';

export class Home extends Component {
    static displayName = Home.name;
    static isEditing = false;
    static editRowIndex = undefined;
    static editColIndex = undefined;

    constructor(props) {
        super(props);
        this.state = { grid: undefined, loading: true };
    }

    componentDidMount() {
        this.populateWeatherData();
    }



    static renderReconciliationTableTitles(titles) {
        return (
            titles.map((item, index) => {
                return <td key={item.month}>{item.monthDisplayName}</td>
            })
        );
    }


    static renderReconciliationTableStatementsOrResults(statementsOrResults, className) {
        return (
            statementsOrResults.map((row, index) => {
                return <tr className={className} key={row.title}>
                    <td>{row.title}</td>
                    {row.values.map(col => {
                        return <td key={col.month}>{col.amount}</td>
                    })}
                </tr>
            })
        );
    }

    static editCell(rowIndex, colIndex) {
        this.isEditing = true;
        this.rowIndex = rowIndex;
        this.colIndex = colIndex;
    }

    static renderReconciliationTableEditableRows(rows) {
        return (
            rows.map((row, rowIndex) => {
                return <tr key={row.incomeOrExpenseTypeName} className={row.flag == 1 ? 'table-success' : 'table-danger'}>
                    <td>{row.incomeOrExpenseTypeName}</td>
                    {row.columns.map((col, colIndex) => {
                        if (!this.isEditing) {
                            return <td key={col.month} title='Click to edit' onClick={() => this.editCell(rowIndex, colIndex)}>{col.amount}</td>

                        } else if (this.isEditing) {
                            return <input type='number' ></input>
                        }
                    })}
                </tr>
            })
        );
    }


    static renderReconciliationTable(grid) {
        return (
            <table className='table table-striped table-bordered' aria-labelledby="tabelLabel">
                <thead>
                    <tr className="text-center">
                        <th colSpan="14">Year {grid.year}</th>
                    </tr>
                    <tr>
                        <td></td>
                        {Home.renderReconciliationTableTitles(grid.titles)}
                    </tr>
                </thead>

                <tbody>
                    {Home.renderReconciliationTableStatementsOrResults(grid.statements, 'table-secondary')}

                    {Home.renderReconciliationTableEditableRows(grid.rows)}

                    {Home.renderReconciliationTableStatementsOrResults(grid.results, 'table-warning')}
                </tbody>
            </table>
        );
    }

    render() {
        let contents = this.state.loading
            ? <p><em>Loading...</em></p>
            : Home.renderReconciliationTable(this.state.grid);

        return (
            <div>
                <h6 id="tabelLabel" className="text-center">We are in React App</h6>
                {contents}


                <div className="row mb-5">
                    <div className="col-12 text-center">
                        <span className="badge badge-secondary">Readonly</span>
                        &nbsp;&nbsp;
                        <span className="badge badge-success">Income</span>
                        &nbsp;&nbsp;
                        <span className="badge badge-danger">Expense</span>
                    </div>
                </div>
            </div>


        );
    }

    async populateWeatherData() {
        const response = await fetch('reconciliation/yearly-table');
        const data = await response.json();
        this.setState({ grid: data, loading: false });
    }
}
